-- Migration: Add treadDepth and construction columns to products table
-- Generated by Drizzle ORM

ALTER TABLE "products" ADD COLUMN "tread_depth" varchar(10);
ALTER TABLE "products" ADD COLUMN "construction" varchar(20);
