-- Migration: Add sale start and end dates to products table
-- Generated by Drizzle ORM

ALTER TABLE "products" ADD COLUMN "sale_start_date" timestamp;
ALTER TABLE "products" ADD COLUMN "sale_end_date" timestamp;
